SELECT [customer_id]
      ,[first_name]
      ,[last_name]
      ,[email]
      ,[address]
      ,[city]
      ,[state]
      ,[phone_number]
      ,[country]
      ,[postal_code]
  FROM [ssis_database_Replica].[dbo].[Customer_Data]
